<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LenovoAMD" failures="0" tests="2" name="Demoproject.ECommerceTest" time="0.851" errors="1" timestamp="2025-08-25T13:34:46 IST" skipped="1">
  <testcase classname="Demoproject.ECommerceTest" name="setUp" time="0.851">
    <error message="Unable to create a new remote session. Please check the server log for more details. Original error: &#039;automationName&#039; is required to be present
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;LENOVOAMD&#039;, ip: &#039;192.168.1.11&#039;, os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.12&#039;
Driver info: driver.version: AndroidDriver
remote stacktrace: InvalidArgumentError: &#039;automationName&#039; is required to be present
    at processCapabilities (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\capabilities.ts:336:13)
    at parseCapsForInnerDriver (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\utils.js:126:38)
    at AppiumDriver.createSession (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:283:49)
    at runCommandPromise (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:116:20)
    at AppiumDriver.executeCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:161:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at defaultBehavior (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:726:16)
    at AppiumDriver.executeWrappedCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:843:16)
    at AppiumDriver.executeCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:742:17)
    at asyncHandler (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.ts:409:19)
Build info: version: &#039;3.141.59&#039;, revision: &#039;e82be7d358&#039;, time: &#039;2018-11-14T08:17:03&#039;
System info: host: &#039;LENOVOAMD&#039;, ip: &#039;192.168.1.11&#039;, os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.12&#039;
Driver info: driver.version: AndroidDriver" type="org.openqa.selenium.SessionNotCreatedException">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: 'automationName' is required to be present
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LENOVOAMD', ip: '192.168.1.11', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.12'
Driver info: driver.version: AndroidDriver
remote stacktrace: InvalidArgumentError: 'automationName' is required to be present
    at processCapabilities (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\capabilities.ts:336:13)
    at parseCapsForInnerDriver (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\utils.js:126:38)
    at AppiumDriver.createSession (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:283:49)
    at runCommandPromise (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:116:20)
    at AppiumDriver.executeCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:161:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at defaultBehavior (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:726:16)
    at AppiumDriver.executeWrappedCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:843:16)
    at AppiumDriver.executeCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:742:17)
    at asyncHandler (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.ts:409:19)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LENOVOAMD', ip: '192.168.1.11', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.12'
Driver info: driver.version: AndroidDriver
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:216)
at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:225)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:250)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:363)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:37)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:89)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:99)
at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:97)
at Demoproject.ECommerceTest.setUp(ECommerceTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:188)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.appium.java_client.remote.AppiumCommandExecutor$1.createSession(AppiumCommandExecutor.java:193)
... 40 more
Caused by: org.openqa.selenium.InvalidArgumentException: 'automationName' is required to be present
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LENOVOAMD', ip: '192.168.1.11', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.12'
Driver info: driver.version: AndroidDriver
remote stacktrace: InvalidArgumentError: 'automationName' is required to be present
    at processCapabilities (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\capabilities.ts:336:13)
    at parseCapsForInnerDriver (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\utils.js:126:38)
    at AppiumDriver.createSession (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:283:49)
    at runCommandPromise (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:116:20)
    at AppiumDriver.executeCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\driver.ts:161:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at defaultBehavior (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:726:16)
    at AppiumDriver.executeWrappedCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:843:16)
    at AppiumDriver.executeCommand (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\lib\appium.js:742:17)
    at asyncHandler (C:\Users\mishr\AppData\Roaming\npm\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.ts:409:19)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
... 45 more
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="Demoproject.ECommerceTest" name="testECommerceFlow" time="0.000">
    <skipped/>
  </testcase> <!-- testECommerceFlow -->
</testsuite> <!-- Demoproject.ECommerceTest -->
